spring.datasource.url=jdbc:h2:mem:dailydelta_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=app_user
spring.datasource.password=${DB_PASSWORD:changeMeStrongPassword}

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update